### ISSUE TITLE
Add support for AES GCM streaming decryption - doUpdate should return the decrypted block

### ISSUE THREAD

**Issue by convoi** [corretto/amazon-corretto-crypto-provider#184]
I'm referring to this comment:  https://github.com/corretto/amazon-corretto-crypto-provider/blob/develop/src/com/amazon/corretto/crypto/provider/AesGcmSpi.java#L43

``` 
* Some random notes:
* For decrypt mode, we buffer all data and process the decryption in doFinal; this is because on older versions of
* OpenSSL, we need to provide the tag before anything else, but this is the last thing that is passed to our API.
* Additionally, this matches JCE behavior.
```

This basically limits decryption to data that fits into memory.
If this is a limitation of older OpenSSL versions, why not switch to a newer one?

BouncyCastle does not have this limitation (but is of course much slower).

**Comment by SalusaSecondus** [comment]
This is not a limitation of OpenSSL but is an intentional decision we made (and which matches that made by the OpenJDK team for their implementation). We will update our comments.

Before the final tag is checked there are no integrity guarantees on the decrypted data and it could have been trivially modified by an attacker. Because of this and the numerous security issues which have resulted, the cryptographic community as a whole is moving away from streaming APIs for authenticated data. You can see this in the new AEAD interfaces exposed by [aws-lc](https://github.com/awslabs/aws-lc/blob/main/include/openssl/aead.h) and [boringssl](https://boringssl.googlesource.com/boringssl/+/master/include/openssl/aead.h).

If you need to encrypt and decrypt very large amounts of data such that it must be done in a streaming manner, I recommend that you do not use AES-GCM directly but use a higher level construction such as that in the [AWS Encryption SDK](https://github.com/aws/aws-encryption-sdk-java) which breaks the stream into smaller authenticated chunks specifically to avoid this security issue.
