### ISSUE TITLE
Compatibility with SunJCE

### ISSUE THREAD

**Issue by smiklosovic** [corretto/amazon-corretto-crypto-provider#315]
Hi,

I am from Apache Cassandra project where we are working on setting this provider as the default one in upcoming Cassandra 5.0 release.

The problem we have with it is that we are not sure how much compatible this library is with what is bundled in JRE. For example, we are afraid that if we make this provider to be the default one, could not it theoretically happen that a user who is on lower version of Cassandra (e.g. 4.0) and wants to upgrade to 5.0 will fail to do so if he is using protocols / ciphers in 4.0 which are not supported in 5.0 because this crypto provider does not support it?

What is the "difference" when it comes to supporting the algos / ciphers / protocols between this and JRE default? Is this provider a subset of JRE one and what is the diff?

@geedo0 @amirhosv thoughts?

**Comment by amirhosv** [comment]
Hi Štefan. With the exception of `AES/XTS/NoPadding` (since version 2.2) and `HkdfWith<mac>` (since version 2.3 - yet-to-be-released), the set of the algorithms and the services provided by ACCP is a subset of SunJCE's and the diff is relatively large. [This doc](https://github.com/corretto/amazon-corretto-crypto-provider/blob/main/DIFFERENCES.md) describes some of the differences in detail.
Some of the algorithms supported by SunJCE are considered weak and as a result they will not become part of ACCP.  Since the diff between ACCP and SunJCE is large it would be best to learn about the algorithms used by Cassandra and add them to ACCP as long as the security guidelines allows.

Here is a full list of services provided by ACCP. The list was generated by [this code](https://github.com/amirhosv/playground/tree/main/jcrypto).
```
Cipher
======
AES/GCM/NoPadding
AES/KWP/NoPadding
AES/XTS/NoPadding
AES_128/GCM/NoPadding
AES_256/GCM/NoPadding
RSA/ECB/NoPadding
RSA/ECB/OAEPPadding
RSA/ECB/OAEPWithSHA-1AndMGF1Padding
RSA/ECB/Pkcs1Padding

KeyAgreement
============
ECDH

KeyFactory
==========
EC
RSA

KeyGenerator
============
AES

KeyPairGenerator
================
EC
RSA

Mac
===
HmacMD5
HmacSHA1
HmacSHA256
HmacSHA384
HmacSHA512

MessageDigest
=============
MD5
SHA-1
SHA-256
SHA-384
SHA-512

SecureRandom
============
LibCryptoRng

Signature
=========
NONEwithECDSA
RSASSA-PSS
SHA1withECDSA
SHA1withECDSAinP1363Format
SHA1withRSA
SHA224withECDSA
SHA224withECDSAinP1363Format
SHA224withRSA
SHA256withECDSA
SHA256withECDSAinP1363Format
SHA256withRSA
SHA384withECDSA
SHA384withECDSAinP1363Format
SHA384withRSA
SHA512withECDSA
SHA512withECDSAinP1363Format
SHA512withRSA

Number of services: 43
```

Services by SunJCE:
```
AlgorithmParameterGenerator
===========================
DiffieHellman

AlgorithmParameters
===================
AES
Blowfish
ChaCha20-Poly1305
DES
DESede
DiffieHellman
GCM
OAEP
PBES2
PBEWithHmacSHA1AndAES_128
PBEWithHmacSHA1AndAES_256
PBEWithHmacSHA224AndAES_128
PBEWithHmacSHA224AndAES_256
PBEWithHmacSHA256AndAES_128
PBEWithHmacSHA256AndAES_256
PBEWithHmacSHA384AndAES_128
PBEWithHmacSHA384AndAES_256
PBEWithHmacSHA512AndAES_128
PBEWithHmacSHA512AndAES_256
PBEWithMD5AndDES
PBEWithMD5AndTripleDES
PBEWithSHA1AndDESede
PBEWithSHA1AndRC2_128
PBEWithSHA1AndRC2_40
PBEWithSHA1AndRC4_128
PBEWithSHA1AndRC4_40
RC2

Cipher
======
AES
AES/GCM/NoPadding
AES/KW/NoPadding
AES/KW/PKCS5Padding
AES/KWP/NoPadding
AES_128/CBC/NoPadding
AES_128/CFB/NoPadding
AES_128/ECB/NoPadding
AES_128/GCM/NoPadding
AES_128/KW/NoPadding
AES_128/KW/PKCS5Padding
AES_128/KWP/NoPadding
AES_128/OFB/NoPadding
AES_192/CBC/NoPadding
AES_192/CFB/NoPadding
AES_192/ECB/NoPadding
AES_192/GCM/NoPadding
AES_192/KW/NoPadding
AES_192/KW/PKCS5Padding
AES_192/KWP/NoPadding
AES_192/OFB/NoPadding
AES_256/CBC/NoPadding
AES_256/CFB/NoPadding
AES_256/ECB/NoPadding
AES_256/GCM/NoPadding
AES_256/KW/NoPadding
AES_256/KW/PKCS5Padding
AES_256/KWP/NoPadding
AES_256/OFB/NoPadding
ARCFOUR
Blowfish
ChaCha20
ChaCha20-Poly1305
DES
DESede
DESedeWrap
PBEWithHmacSHA1AndAES_128
PBEWithHmacSHA1AndAES_256
PBEWithHmacSHA224AndAES_128
PBEWithHmacSHA224AndAES_256
PBEWithHmacSHA256AndAES_128
PBEWithHmacSHA256AndAES_256
PBEWithHmacSHA384AndAES_128
PBEWithHmacSHA384AndAES_256
PBEWithHmacSHA512AndAES_128
PBEWithHmacSHA512AndAES_256
PBEWithMD5AndDES
PBEWithMD5AndTripleDES
PBEWithSHA1AndDESede
PBEWithSHA1AndRC2_128
PBEWithSHA1AndRC2_40
PBEWithSHA1AndRC4_128
PBEWithSHA1AndRC4_40
RC2
RSA

KeyAgreement
============
DiffieHellman

KeyFactory
==========
DiffieHellman

KeyGenerator
============
AES
ARCFOUR
Blowfish
ChaCha20
DES
DESede
HmacMD5
HmacSHA1
HmacSHA224
HmacSHA256
HmacSHA3-224
HmacSHA3-256
HmacSHA3-384
HmacSHA3-512
HmacSHA384
HmacSHA512
HmacSHA512/224
HmacSHA512/256
RC2
SunTls12Prf
SunTlsKeyMaterial
SunTlsMasterSecret
SunTlsPrf
SunTlsRsaPremasterSecret

KeyPairGenerator
================
DiffieHellman

KeyStore
========
JCEKS

Mac
===
HmacMD5
HmacPBESHA1
HmacPBESHA224
HmacPBESHA256
HmacPBESHA384
HmacPBESHA512
HmacPBESHA512/224
HmacPBESHA512/256
HmacSHA1
HmacSHA224
HmacSHA256
HmacSHA3-224
HmacSHA3-256
HmacSHA3-384
HmacSHA3-512
HmacSHA384
HmacSHA512
HmacSHA512/224
HmacSHA512/256
PBEWithHmacSHA1
PBEWithHmacSHA224
PBEWithHmacSHA256
PBEWithHmacSHA384
PBEWithHmacSHA512
SslMacMD5
SslMacSHA1

SecretKeyFactory
================
DES
DESede
PBEWithHmacSHA1AndAES_128
PBEWithHmacSHA1AndAES_256
PBEWithHmacSHA224AndAES_128
PBEWithHmacSHA224AndAES_256
PBEWithHmacSHA256AndAES_128
PBEWithHmacSHA256AndAES_256
PBEWithHmacSHA384AndAES_128
PBEWithHmacSHA384AndAES_256
PBEWithHmacSHA512AndAES_128
PBEWithHmacSHA512AndAES_256
PBEWithMD5AndDES
PBEWithMD5AndTripleDES
PBEWithSHA1AndDESede
PBEWithSHA1AndRC2_128
PBEWithSHA1AndRC2_40
PBEWithSHA1AndRC4_128
PBEWithSHA1AndRC4_40
PBKDF2WithHmacSHA1
PBKDF2WithHmacSHA224
PBKDF2WithHmacSHA256
PBKDF2WithHmacSHA384
PBKDF2WithHmacSHA512

Number of services: 161
```

**Comment by geedo0** [comment]
Yes, Java JCE will walk through all the installed providers in order of preference when trying to resolve a particular implementation.

**Comment by amirhosv** [comment]
The only exception I see to this is if the client code asks for an algorithm from a specific provider. [This](https://github.com/felx/nimbus-jose-jwt/blob/master/src/main/java/com/nimbusds/jose/crypto/AESGCM.java#L111-L113) is one example from Nimbus; if the provider is passed explicitly and it does not have the algorithm, it fails. There are legitimate use cases for specifying the provider when asking for an algorithm; for example, it may not be possible to install a provider due to a security policy or the client code needs to ensure the algorithms are coming from a "certified" provider.

**Comment by smiklosovic** [comment]
@geedo0  @amirhosv  we decided to make Corretto default crypto provider for new clusters
