### ISSUE TITLE
The JCE Provider example.jar is not signed.

### ISSUE THREAD

**Issue by JohannesLichtenberger** [corretto/amazon-corretto-crypto-provider#351]
How do I avoid this failure?

```
Caused by: java.util.jar.JarException: The JCE Provider file:/path/to/sirix-query-0.10.0-all.jar is not signed.
    at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:469)
    at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:320)
    at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:263)
    at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
    at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:196)
    at java.base/javax.crypto.JceSecurity$2.apply(JceSecurity.java:222)
    at java.base/javax.crypto.JceSecurity$2.apply(JceSecurity.java:211)
    at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
```

**Comment by alexw91** [comment]
"The JCE Provider file:/path/to/sirix-query-0.10.0-all.jar is not signed."

This looks like an issue with the sirix-query jar file, not the AmazonCorrettoCryptoProvider jar file.

**Comment by alexw91** [comment]
Are you unzipping ACCP's jar file contents and bundling them into `sirix-query-0.10.0-all.jar`? This may not work on OracleJdk as they require all jar files that install Java Cryptography Extentions (JCE) providers be signed by Oracle's JCE signing key. The jars that ACCP uploads to Maven should already be signed with Oracle's keys, but that signature will break if ACCP's jar file is modified or repackaged into another jar file. 

If this is the case, then the potential options for you are the following:
 1. Migrate to a different JDK (eg OpenJDK or CorrettoJDK) since other JDK's don't enable this signature checking by default as far as I'm aware.
 2. Don't unzip and copy ACCP's jar file contents into `sirix-query-0.10.0-all.jar`. Keep ACCP's jar file unmodified so that ACCP's signature check will pass.
 3. [Go through the process](https://www.oracle.com/java/technologies/javase/getcodesigningcertificate.html) to have `sirix-query-0.10.0-all.jar` signed by Oracle.

**Comment by JohannesLichtenberger** [comment]
Yes, for now I've removed the dependency, sadly.

Don't know what Gradle does right now to create the "fat" JAR though

**Comment by alexw91** [comment]
Do you have steps to reproduce this issue? Having the specific build commands or links to the build files used would be helpful for us to take a look and figure out if we can provide better documentation on how to exclude ACCP when creating fat jars.

**Comment by JohannesLichtenberger** [comment]
The parent gradle file is this: https://github.com/sirixdb/sirix/blob/main/build.gradle

**Comment by geedo0** [comment]
@alexw91 investigated the behavior around re-bundling signed jars and updated our guidance. Please see the PR above for how to work around this issue.
