### ISSUE TITLE
Why OpenSSL instead of s2n?

### ISSUE THREAD

**Issue by jaxley** [corretto/amazon-corretto-crypto-provider#42]
Curious that this would re-introduce OpenSSL where AWS has made great strides to replace it with s2n, which is "simple, small, fast and with security as a priority"

Are there plans to ensure that s2n will be used as the primary crypto engine and set up a roadmap for implementing additional JCE supported algorithms so you can minimize the OpenSSL usage?  Perhaps you could even split and have two different versions:  one that only uses s2n and another that uses OpenSSL so if you wanted more security but fewer options you could choose that route?

**Comment by SalusaSecondus** [comment]
s2n doesn't (currently) provide any cryptographic implementations but instead depends on another library to actually implement the ciphers. (As per its current [readme](https://github.com/awslabs/s2n/blob/master/README.md) this includes "OpenSSL, LibreSSL, BoringSSL, and the Apple Common Crypto framework".)

So, s2n doesn't solve the implementation problem for us, nor are they likely to in the near future as they are solving a different problem (TLS rather than cryptography). We may look at other cryptographic implementations in the future but felt that OpenSSL was the correct implementation to start with.
