### ISSUE TITLE
Support Jetty Client to make outbound calls 

### ISSUE THREAD

**Issue by nomstradamus** [corretto/amazon-corretto-crypto-provider#74]
We would like the jetty async client to use the amazon crypt provider for handling outgoing https calls natively.  Can you let me know if this is currently supported and how to enable it .

Please refer to https://www.eclipse.org/jetty/documentation/9.4.x/configuring-ssl.html#conscrypt

**Comment by SalusaSecondus** [comment]
The Amazon Corretto Crypto Provider provides low-level cryptographic implementations to all consumers, including the `SunJSSE` JSSE provider. Based on my understanding of the [Jetty documentation](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-ssl-distribution.html#_default_jsse_ssl_configuration) is that Jetty will use SunJSSE for TLS unless specifically configured not to do so. Since `SunJSSE` will use ACCP internally, all that should be necessary to use ACCP with Jetty is to enable/install ACCP as per our [standard documentation](https://github.com/corretto/amazon-corretto-crypto-provider/blob/master/README.md) and not modify the Jetty configuration at all.

If this does not work, please let us know and we'll look into this further.

**Comment by SalusaSecondus** [comment]
(We'll close this issue soon if we don't hear back.)
